name: Build
run-name: ${{ gitea.actor }} 

on:
  push:
    branches: [main, dev]
    paths:
      - 'Dockerfile'
      - 'server.ts'
      - 'database.ts'
      - 'public/**'
      - '**/build.yml'
  pull_request:
    branches: [main]
    paths:
      - 'Dockerfile'
      - 'server.ts'
      - 'database.ts'
      - 'public/**'
      - '**/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Gitea container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ gitea.actor }}
          password: ${{ secrets.GITEA_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ vars.REGISTRY }}/${{ gitea.repository }}:${{ gitea.sha }}
            ${{ vars.REGISTRY }}/${{ gitea.repository }}:latest
