name: Build
run-name: ${{ gitea.actor }} 

on:
  push:
    branches: [main, dev]
    paths:
      - 'Dockerfile'
      - 'server.ts'
      - 'database.ts'
      - 'public/**'
      - 'build.yml'
  pull_request:
    branches: [main]
    paths:
      - 'Dockerfile'
      - 'server.ts'
      - 'database.ts'
      - 'public/**'
      - 'build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t rcw-reader:${{ gitea.sha }} .
